permission:
  enabled: false
backend:
  baseUrl: ${BASE_URL}
  https: true
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    # Plugin: Jira
    img-src:
      # "'self'" and 'data' are from the backstage default but must be set since img-src is overwritten
      - "'self'"
      - 'data:'
      # Allow your Jira instance for @roadiehq/backstage-plugin-jira
      - ${JIRA_URL}
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

# comment out the following 'database' section to use the PostgreSQL database
  database:
    client: better-sqlite3
    connection: ':memory:'

  auth:
    keys:
      - secret: "development"

signInPage: rhaap
auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    rhaap:
      development:
        host: ${RHAAP_HOST}
        checkSSL: false
        clientId: ${RHAAP_OAUTH_CLIENT_ID}
        clientSecret: ${RHAAP_OAUTH_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUser
# Plugin: Permission

# dangerouslyAllowSignInWithoutUserInCatalog: true

app:
  title: RHDH
  baseUrl: ${BASE_URL}

ansible:
  rhaap:
    baseUrl: ${RHAAP_HOST}
    token: ${RHAAP_TOKEN}
    checkSSL: false
    showCaseLocation:
      type: file
      target: '/tmp/aap-showcases/'
    schedule:
      frequency:
        seconds: 30
      timeout:
        seconds: 5
  creatorService:
    baseUrl: '127.0.0.1'
    port: '8000'

catalog:
  stitchingStrategy:
    immediate: true
  orphanStrategy: delete
  processingInterval: { seconds: 10 }
  pollingInterval: { seconds: 1 }
  stitchTimeout: { minutes: 1 }
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        [Component, System, Group, Resource, Location, Template, API, Users]
  locations:
    - type: url
      target: https://github.com/ansible/ansible-rhdh-templates/blob/main/seed.yaml
      rules:
        - allow: [Template]
    - type: file
      target: /tmp/aap-showcases/all.yaml
      rules:
        - allow: [Template]
  providers:
    rhaap:
      development:
        schedule:
          frequency: { minutes: 1 }
          timeout: { seconds: 5 }
enableExperimentalRedirectFlow: true
