signInPage: rhaap
auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    # github:
    #   development:
    #     clientId: ${AUTH_GITHUB_CLIENT_ID}
    #     clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    rhaap:
      development:
        host: ${RHAAP_HOST}
        clientId: ${RHAAP_OAUTH_CLIENT_ID}
        clientSecret: ${RHAAP_OAUTH_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUser

# integrations:
#   github:
#     - host: github.com
#       apps:
#         - $include: github-app-credentials.yaml

app:
  title: RHDH
  baseUrl: ${BASE_URL}

backend:
  listen:
    port: 7007
  baseUrl: ${BASE_URL}
  https: true
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

# comment out the following 'database' section to use the PostgreSQL database
  database:
    client: better-sqlite3
    connection: ':memory:'

  auth:
    keys:
      - secret: "development"

# You can use local files from catalog-entities directory to load entities into the catalog
catalog:

  rules:
    - allow: [Component, API, Location, Template, Domain, User, Group, System, Resource]

  locations:
    - type: file
      target: /opt/app-root/src/configs/catalog-entities/users.yaml
      rules:
        - allow: [User, Group]
    - type: file
      target: /opt/app-root/src/configs/catalog-entities/components.yaml
      rules:
        - allow: [Component, System]
    # - type: url
    #   target: https://github.com/backstage/backstage/blob/master/packages/catalog-model/examples/all.yaml
    #   rules:
    #     - allow: [Component, User, Group, Domain]
  providers:
    rhaap:
      development:
        baseUrl: ${RHAAP_HOST}
        clientId: ${RHAAP_CATALOG_OAUTH_CLIENT_ID}
        clientSecret: ${RHAAP_CATALOG_OAUTH_CLIENT_SECRET}
        user: ${RHAAP_CATALOG_USER}
        password: ${RHAAP_CATALOG_PASSWORD}
        schedule:
          frequency:
            minutes: 1
          timeout:
            minutes: 1
          initialDelay:
            seconds: 15

techdocs:
  generator:
    runIn: local
  builder: local
  publisher: 
    type: local
