permission:
  enabled: false
backend:
  baseUrl: ${BASE_URL}
  # https: true
  listen:
    port: 7007
    # Uncomment the following host directive to bind to specific interfaces
    # host: 127.0.0.1
  csp:
    # Content-Security-Policy directives follow the Helmet format: https://helmetjs.github.io/#reference
    # Default Helmet Content-Security-Policy values can be removed by setting the key to false
    connect-src:
      - "'self'"
      - 'http:'
      - 'https:'
    # Plugin: Jira
    img-src:
      # "'self'" and 'data' are from the backstage default but must be set since img-src is overwritten
      - "'self'"
      - 'data:'
      # Allow your Jira instance for @roadiehq/backstage-plugin-jira
      - ${JIRA_URL}
  cors:
    origin: ${BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

# comment out the following 'database' section to use the PostgreSQL database
  database:
    client: better-sqlite3
    connection: ':memory:'

  auth:
    keys:
      - secret: "development"

signInPage: rhaap
auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    rhaap:
      development:
        host: ${RHAAP_HOST}
        checkSSL: false
        clientId: ${RHAAP_OAUTH_CLIENT_ID}
        clientSecret: ${RHAAP_OAUTH_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUser
# Plugin: Permission

# dangerouslyAllowSignInWithoutUserInCatalog: true

app:
  title: RHDH
  baseUrl: ${BASE_URL}
  branding:
    fullLogo: data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI5MzIuNjYiIGhlaWdodD0iMjM5LjE5IiB2aWV3Qm94PSIwIDAgOTMyLjY2IDIzOS4xOSI+CiAgPGRlZnM+CiAgICA8c3R5bGU+CiAgICAgIC5jbHMtMSB7CiAgICAgICAgZmlsbDogI2ZmZjsKICAgICAgfQogICAgPC9zdHlsZT4KICA8L2RlZnM+CiAgPGc+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNyw4My40OGMxMi42MywwLDMwLjc2LTIuNDcsMzAuNzYtMTcuNTgsMC0xLjEsMC0yLjItLjI3LTMuNTdsLTcuNDEtMzIuNDFjLTEuNjUtNy4xNC0zLjMtMTAuNDQtMTUuOTMtMTYuNzVDMTI0Ljk1LDguMjQsMTAzLjgxLDAsOTcuNDksMGMtNS43NywwLTcuNDEsNy40MS0xNC41NSw3LjQxLTYuNTksMC0xMS44MS01Ljc3LTE3Ljg1LTUuNzdzLTkuODksNC4xMi0xMi45MSwxMi42M2MwLDAtOC41MSwyMy44OS05LjYxLDI3LjE5LS4yNy41NS0uMjcsMS4zNy0uMjcsMS45MiwwLDkuNjEsMzYuNTIsNDAuMDksODUuNDEsNDAuMDlNMTYwLjM4LDcxLjk1YzEuNjUsOC4yNCwxLjY1LDkuMDYsMS42NSwxMC4xNiwwLDE0LjAxLTE1LjkzLDIxLjk3LTM2LjUyLDIxLjk3LTQ2Ljk2LDAtODguMTUtMjcuNDYtODguMTUtNDUuODYsMC0yLjQ3LjU1LTQuOTQsMS42NS03LjQxQzIxLjk3LDUxLjksMCw1NC45MiwwLDc0LjE1YzAsMzEuODYsNzQuOTcsNzAuODUsMTM0LjI5LDcwLjg1LDQ1LjU5LDAsNTcuMTItMjAuNiw1Ny4xMi0zNi44LDAtMTIuOTEtMTAuOTgtMjcuNDYtMzEuMDMtMzYuMjUiLz4KICAgIDxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTU4Mi40Nyw5Mi44MmMwLDEyLjA4LDcuMTQsMTcuODUsMjAuMzIsMTcuODUsNC4xMiwwLDcuOTYtLjU1LDEyLjA4LTEuNjV2LTEzLjczYy0yLjQ3LjgyLTUuMjIsMS4xLTcuNjksMS4xLTUuNDksMC03LjQxLTEuNjUtNy40MS02Ljg3di0yMS4xNWgxNS42NXYtMTQuMjhoLTE1LjY1di0xOC4xM2wtMTcuMDMsMy41N3YxNC4yOGgtMTEuMjZ2MTQuMjhoMTEuMjZ2MjQuNzJoLS4yN1pNNTI5LjIsOTMuMzdjMC0zLjU3LDMuODQtNS40OSw5LjM0LTUuNDksMy4zLDAsNi44Ny41NSwxMC4xNiwxLjM3djcuMTRjLTMuMywxLjkyLTYuODcsMi43NS0xMC43MSwyLjc1LTUuNDktLjI3LTguNzktMi40Ny04Ljc5LTUuNzdNNTM0LjQxLDExMC45NWM2LjA0LDAsMTAuOTgtMS4zNywxNS4zOC00LjM5djMuM2gxNy4wM3YtMzUuOThjMC0xMy43My05LjA2LTIxLjE1LTI0LjQ0LTIxLjE1LTguNTEsMC0xNy4wMywxLjkyLTI2LjA5LDYuMDRsNi4wNCwxMi42M2M2LjU5LTIuNzUsMTIuMDgtNC4zOSwxNy4wMy00LjM5LDcuMTQsMCwxMC43MSwyLjc1LDEwLjcxLDguMjR2Mi43NWMtNC4xMi0xLjEtOC41MS0xLjY1LTEyLjYzLTEuNjUtMTQuMjgsMC0yMy4wNyw2LjA0LTIzLjA3LDE2Ljc1LS4yNywxMC40NCw3LjQxLDE3Ljg1LDIwLjA1LDE3Ljg1TTQ0MS4zMiwxMTAuMTJoMTguMTN2LTI5LjExaDMwLjQ4djI5LjExaDE4LjEzVjM1Ljk4aC0xOC4xM3YyOC41NmgtMzAuNDh2LTI4LjU2aC0xOC4xM3Y3NC4xNVpNMzcyLjExLDgxLjg0YzAtNy45Niw2LjMyLTE0LjI4LDE0LjgzLTE0LjI4LDQuMzksMCw4LjUxLDEuMzcsMTEuODEsNC4zOXYxOS41Yy0zLjMsMy4wMi03LjQxLDQuNjctMTEuODEsNC4zOS04LjI0LjI3LTE0LjgzLTUuNzctMTQuODMtMTQuMDFNMzk4Ljc1LDExMC4xMmgxNy4wM1YzMi40MWwtMTcuMDMsMy41N3YyMS4xNWMtNC4zOS0yLjQ3LTkuMzQtMy44NC0xNC4yOC0zLjU3LTE2LjIsMC0yOS4xMSwxMi42My0yOS4xMSwyOC41Ni0uMjcsMTUuNjUsMTIuMzYsMjguNTYsMjguMDEsMjguODRoLjU1YzUuNDksMCwxMC43MS0xLjY1LDE1LjEtNC45NGwtLjI3LDQuMTJaTTMyMS4zMSw2Ny4wMWM1LjQ5LDAsOS44OSwzLjU3LDExLjgxLDguNzloLTIzLjM0YzEuNjUtNS40OSw1Ljc3LTguNzksMTEuNTMtOC43OU0yOTIuNDcsODIuMTFjMCwxNi4yLDEzLjQ2LDI5LjExLDMwLjQ4LDI5LjExLDkuMzQsMCwxNi4yLTIuNDcsMjMuMzQtOC41MWwtMTEuMjYtMTAuMTZjLTIuNzUsMi43NS02LjU5LDQuMTItMTEuMjYsNC4xMi02LjA0LjI3LTExLjUzLTMuMy0xMy43My04Ljc5aDM5Ljgydi00LjEyYzAtMTcuODUtMTEuODEtMzAuNDgtMjguMjktMzAuNDgtMTUuOTMtLjI3LTI4Ljg0LDEyLjM2LTI5LjExLDI4LjI5LDAsMCwwLC4yNywwLC41NU0yNjIuODEsNTEuMzVjNi4wNCwwLDkuMzQsMy44NCw5LjM0LDguMjRzLTMuMyw4LjI0LTkuMzQsOC4yNGgtMTcuODV2LTE2Ljc1aDE3Ljg1di4yN1pNMjI2Ljg0LDEwOS44NWgxOC4xMnYtMjYuOTFoMTMuNzNsMTQuMDEsMjYuOTFoMjAuMzJsLTE2LjItMjkuNjZjOC41MS0zLjU3LDE0LjAxLTExLjgxLDE0LjAxLTIwLjg3LDAtMTMuNDYtMTAuNDQtMjMuNjItMjYuMDktMjMuNjJoLTM3Ljl2NzQuMTVaIi8+CiAgPC9nPgogIDxnPgogICAgPHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMjE5LDIzOC4wN2wzMi4yNi03OC40aDE2LjEzbDMyLjAzLDc4LjRoLTE1LjAxbC04LjYyLTIxLjg0aC0zMy44MmwtOC42MiwyMS44NGgtMTQuMzRaTTI0Ni40NCwyMDQuOTJoMjUuMDlsLTEyLjU0LTMxLjgxLTEyLjU0LDMxLjgxWiIvPgogICAgPHBhdGggY2xhc3M9ImNscy0xIiBkPSJNMzA1LjU4LDIzOC4wN3YtNTcuNjhoMTMuMXY1LjM4YzQuNC00LjMzLDEwLTYuNSwxNi44LTYuNSw0LjQsMCw4LjMxLjk3LDExLjcsMi45MSwzLjQsMS45NCw2LjA3LDQuNjEsOC4wMSw4LjAxLDEuOTQsMy40LDIuOTEsNy4zNywyLjkxLDExLjkzdjM1Ljk1aC0xMy4xdi0zMy45NGMwLTQuMTgtMS4yLTcuNDctMy41OC05Ljg2LTIuMzktMi4zOS01LjYtMy41OC05LjYzLTMuNTgtMi44NCwwLTUuMzYuNTgtNy41NiwxLjc0LTIuMiwxLjE2LTQuMDUsMi43OC01LjU0LDQuODd2NDAuNzdoLTEzLjFaIi8+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0zOTEuMDMsMjM5LjE5Yy01LjE1LDAtOS45My0uNzEtMTQuMzQtMi4xMy00LjQxLTEuNDItOC4yMS0zLjQ3LTExLjQyLTYuMTZsNi43Mi04Ljc0YzMuMjEsMi4zOSw2LjM2LDQuMTYsOS40Niw1LjMyLDMuMSwxLjE2LDYuMjIsMS43NCw5LjM1LDEuNzQsMy43MywwLDYuNzYtLjY5LDkuMDctMi4wNywyLjMxLTEuMzgsMy40Ny0zLjE5LDMuNDctNS40MywwLTEuNzktLjY3LTMuMjEtMi4wMi00LjI2LTEuMzQtMS4wNC0zLjQ0LTEuNzktNi4yNy0yLjI0bC0xMC43NS0xLjU3Yy01Ljc1LS44Mi0xMC4wOC0yLjYzLTEyLjk5LTUuNDMtMi45MS0yLjgtNC4zNy02LjQ4LTQuMzctMTEuMDMsMC0zLjU4Ljk1LTYuNywyLjg2LTkuMzUsMS45LTIuNjUsNC42MS00LjcyLDguMTItNi4yMiwzLjUxLTEuNDksNy42Mi0yLjI0LDEyLjMyLTIuMjQsNC4xOCwwLDguMjMuNiwxMi4xNSwxLjc5LDMuOTIsMS4yLDcuNjMsMy4wMiwxMS4xNCw1LjQ5bC02LjM4LDguNjJjLTMuMjEtMi4wMi02LjI3LTMuNDktOS4xOC00LjQyLTIuOTEtLjkzLTUuODYtMS40LTguODUtMS40LTMuMTQsMC01LjY2LjYyLTcuNTYsMS44NS0xLjksMS4yMy0yLjg2LDIuODktMi44Niw0Ljk4LDAsMS44Ny42NywzLjMsMi4wMiw0LjMxLDEuMzQsMS4wMSwzLjU4LDEuNzQsNi43MiwyLjE4bDEwLjY0LDEuNTdjNS43NS43NSwxMC4xMiwyLjUyLDEzLjEsNS4zMiwyLjk5LDIuOCw0LjQ4LDYuNDQsNC40OCwxMC45MiwwLDMuNTgtMS4wOCw2Ljc4LTMuMjUsOS41OC0yLjE3LDIuOC01LjEsNS04Ljc5LDYuNjEtMy43LDEuNi03LjksMi40MS0xMi42LDIuNDFaIi8+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik00MzAuMzQsMTcyLjIyYy0yLjA5LDAtMy45LS43NS01LjQzLTIuMjQtMS41My0xLjQ5LTIuMy0zLjMyLTIuMy01LjQ5cy43Ny0zLjk5LDIuMy01LjQ5YzEuNTMtMS40OSwzLjM0LTIuMjQsNS40My0yLjI0czMuOTkuNzUsNS40OSwyLjI0YzEuNDksMS41LDIuMjQsMy4zMiwyLjI0LDUuNDlzLS43NSw0LTIuMjQsNS40OWMtMS40OSwxLjQ5LTMuMzIsMi4yNC01LjQ5LDIuMjRaTTQyMy44NSwyMzguMDd2LTU3LjY4aDEzLjF2NTcuNjhoLTEzLjFaIi8+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik00NDkuNjEsMjM4LjA3di03OC40bDEzLjEtMi4zNXYyOC4xMWM0LjctMy44OCwxMC4zLTUuODIsMTYuOC01LjgyLDUuNTIsMCwxMC40OSwxLjMzLDE0LjksMy45OCw0LjQsMi42NSw3LjksNi4yLDEwLjQ3LDEwLjY0LDIuNTgsNC40NCwzLjg2LDkuNDYsMy44NiwxNS4wNnMtMS4zMSwxMC41My0zLjkyLDE1LjAxYy0yLjYxLDQuNDgtNi4xNCw4LjA1LTEwLjU4LDEwLjctNC40NCwyLjY1LTkuNDMsMy45OC0xNC45NSwzLjk4LTMuMDYsMC02LjAzLS40Ny04LjktMS40LTIuODgtLjkzLTUuNTEtMi4yNi03LjktMy45OHY0LjQ4aC0xMi44OFpNNDc3LjYxLDIyNy42NmMzLjUxLDAsNi42My0uOCw5LjM1LTIuNDEsMi43My0xLjYsNC44OS0zLjc5LDYuNS02LjU1LDEuNi0yLjc2LDIuNDEtNS45LDIuNDEtOS40MXMtLjgtNi42NC0yLjQxLTkuNDFjLTEuNjEtMi43Ni0zLjc5LTQuOTUtNi41NS02LjU1LTIuNzYtMS42LTUuODYtMi40MS05LjMtMi40MS0yLjk5LDAtNS43Ny41NC04LjM0LDEuNjItMi41OCwxLjA4LTQuNzYsMi42My02LjU1LDQuNjV2MjQuM2MxLjcyLDEuOTQsMy45LDMuNDYsNi41NSw0LjU0LDIuNjUsMS4wOCw1LjQzLDEuNjIsOC4zNCwxLjYyWiIvPgogICAgPHBhdGggY2xhc3M9ImNscy0xIiBkPSJNNTE4LjgyLDIzOC4wN3YtNzguNGwxMy4xLTIuMzV2ODAuNzVoLTEzLjFaIi8+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik01NzIuNDcsMjM5LjA4Yy01Ljc1LDAtMTAuOTItMS4zMS0xNS41MS0zLjkyLTQuNTktMi42MS04LjI1LTYuMTgtMTAuOTgtMTAuNy0yLjczLTQuNTItNC4wOS05LjU4LTQuMDktMTUuMThzMS4zMS0xMC42NCwzLjkyLTE1LjEyYzIuNjEtNC40OCw2LjEyLTguMDQsMTAuNTMtMTAuNyw0LjQtMi42NSw5LjMzLTMuOTgsMTQuNzgtMy45OHMxMC4yOCwxLjM0LDE0LjUsNC4wM2M0LjIyLDIuNjksNy41Niw2LjMzLDEwLjAyLDEwLjkyczMuNyw5LjgsMy43LDE1LjYydjMuNDdoLTQ0LjEzYy42LDIuODQsMS43Miw1LjM0LDMuMzYsNy41LDEuNjQsMi4xNywzLjczLDMuODYsNi4yNyw1LjEsMi41NCwxLjIzLDUuMjYsMS44NSw4LjE4LDEuODUsMi42OSwwLDUuMjQtLjQxLDcuNjctMS4yMywyLjQzLS44Miw0LjQ2LTIuMDIsNi4xLTMuNThsOC41MSw4LjA2Yy0zLjQ0LDIuNjktNi45OCw0LjY3LTEwLjY0LDUuOTQtMy42NiwxLjI3LTcuNzMsMS45LTEyLjIxLDEuOVpNNTU1LjExLDIwNC4wMmgzMS4yNWMtLjUyLTIuNjktMS41My01LjA0LTMuMDItNy4wNi0xLjQ5LTIuMDItMy4zLTMuNi01LjQzLTQuNzYtMi4xMy0xLjE2LTQuNDYtMS43NC03LTEuNzRzLTUuMDIuNTYtNy4yMiwxLjY4Yy0yLjIsMS4xMi00LjAzLDIuNjktNS40OSw0LjctMS40NiwyLjAyLTIuNDgsNC40MS0zLjA4LDcuMTdaIi8+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik02MzMuNjIsMjM4LjA3di03OC40aDM3LjYzYzUuMTUsMCw5LjY3LDEuMDEsMTMuNTUsMy4wMiwzLjg4LDIuMDIsNi45MSw0LjgzLDkuMDcsOC40NiwyLjE2LDMuNjIsMy4yNSw3Ljc4LDMuMjUsMTIuNDlzLTEuMDgsOC43NC0zLjI1LDEyLjMyYy0yLjE3LDMuNTgtNS4yMSw2LjQtOS4xMyw4LjQ2LTMuOTIsMi4wNS04LjQyLDMuMDgtMTMuNSwzLjA4aC0yMy44NnYzMC41OGgtMTMuNzhaTTY0Ny40LDE5NS44NWgyMi40YzQuMTEsMCw3LjM3LTEuMSw5LjgtMy4zLDIuNDMtMi4yLDMuNjQtNS4xMywzLjY0LTguNzlzLTEuMjEtNi41OS0zLjY0LTguNzljLTIuNDMtMi4yLTUuNjktMy4zLTkuOC0zLjNoLTIyLjR2MjQuMTlaIi8+CiAgICA8cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik03MjkuMjcsMjM5LjE5Yy01LjY4LDAtMTAuODEtMS4zMy0xNS40LTMuOTgtNC41OS0yLjY1LTguMjMtNi4yMy0xMC45Mi0xMC43NS0yLjY5LTQuNTItNC4wMy05LjU4LTQuMDMtMTUuMThzMS4zNC0xMC42Niw0LjAzLTE1LjE4YzIuNjktNC41Miw2LjMzLTguMSwxMC45Mi0xMC43NSw0LjU5LTIuNjUsOS43Mi0zLjk4LDE1LjQtMy45OHMxMC45MiwxLjMzLDE1LjUxLDMuOThjNC41OSwyLjY1LDguMjMsNi4yNCwxMC45MiwxMC43NSwyLjY5LDQuNTIsNC4wMyw5LjU4LDQuMDMsMTUuMThzLTEuMzQsMTAuNjYtNC4wMywxNS4xOGMtMi42OSw0LjUyLTYuMzMsOC4xLTEwLjkyLDEwLjc1LTQuNTksMi42NS05Ljc2LDMuOTgtMTUuNTEsMy45OFpNNzI5LjI3LDIyNy43N2MzLjI4LDAsNi4yNS0uODIsOC45LTIuNDYsMi42NS0xLjY0LDQuNzYtMy44Niw2LjMzLTYuNjYsMS41Ny0yLjgsMi4zNS01LjkyLDIuMzUtOS4zNXMtLjc4LTYuNjQtMi4zNS05LjQxYy0xLjU3LTIuNzYtMy42OC00Ljk2LTYuMzMtNi42MS0yLjY1LTEuNjQtNS41OC0yLjQ2LTguNzktMi40NnMtNi4yNy44Mi04Ljk2LDIuNDZjLTIuNjksMS42NC00LjgsMy44NS02LjMzLDYuNjEtMS41MywyLjc2LTIuMyw1LjktMi4zLDkuNDFzLjc2LDYuNTUsMi4zLDkuMzVjMS41MywyLjgsMy42Miw1LjAyLDYuMjcsNi42NiwyLjY1LDEuNjQsNS42MiwyLjQ2LDguOSwyLjQ2WiIvPgogICAgPHBhdGggY2xhc3M9ImNscy0xIiBkPSJNNzY5LjgxLDIzOC4wN3YtNTcuNjhoMTMuMXY2Ljk0YzEuNzktMi42MSw0LjAxLTQuNjMsNi42Ni02LjA1LDIuNjUtMS40Miw1LjYyLTIuMTMsOC45LTIuMTMsMi42MSwwLDQuNjMuMzgsNi4wNSwxLjEydjExLjY1Yy0xLjA1LS41Mi0yLjE4LS45LTMuNDItMS4xMi0xLjIzLS4yMi0yLjQ4LS4zNC0zLjc1LS4zNC0zLjE0LDAtNS45Ni44Mi04LjQ2LDIuNDYtMi41LDEuNjQtNC41LDQtNS45OSw3LjA2djM4LjA4aC0xMy4xWiIvPgogICAgPHBhdGggY2xhc3M9ImNscy0xIiBkPSJNODM5LjE0LDIzOS4wOGMtNS45NywwLTEwLjUxLTEuMzgtMTMuNjEtNC4xNC0zLjEtMi43Ni00LjY1LTYuNzktNC42NS0xMi4xdi0zMS4zNmgtMTIuMXYtMTEuMDloMTIuMXYtMTQuNjdsMTMuMS0zLjAydjE3LjdoMTYuNjl2MTEuMDloLTE2LjY5djI4LjU2YzAsMi44NC42Miw0Ljg1LDEuODUsNi4wNSwxLjIzLDEuMiwzLjM0LDEuNzksNi4zMywxLjc5LDEuNTcsMCwyLjk3LS4xMSw0LjItLjM0LDEuMjMtLjIyLDIuNTYtLjU2LDMuOTgtMS4wMXYxMC44NmMtMS40OS41Mi0zLjMyLjkzLTUuNDksMS4yMy0yLjE3LjMtNC4wNy40NS01LjcxLjQ1WiIvPgogICAgPHBhdGggY2xhc3M9ImNscy0xIiBkPSJNODc2Ljk5LDIzOS4wOGMtNC4xMSwwLTcuNzUtLjc1LTEwLjkyLTIuMjQtMy4xNy0xLjQ5LTUuNjYtMy41Ni03LjQ1LTYuMjItMS43OS0yLjY1LTIuNjktNS42OS0yLjY5LTkuMTMsMC01LjUyLDIuMDctOS44Miw2LjIyLTEyLjg4LDQuMTQtMy4wNiw5Ljg0LTQuNTksMTcuMDgtNC41OSw1LjM4LDAsMTAuMzguOSwxNS4wMSwyLjY5di01LjE1YzAtMy43My0xLjEtNi41My0zLjMtOC40LTIuMi0xLjg3LTUuNDctMi44LTkuOC0yLjgtMi41NCwwLTUuMjMuMzctOC4wNiwxLjEyLTIuODQuNzUtNi4wOSwxLjk4LTkuNzQsMy43bC00LjctOS44NmM0LjQtMi4wMiw4LjU5LTMuNTMsMTIuNTQtNC41NCwzLjk2LTEuMDEsNy45NS0xLjUxLDExLjk4LTEuNTEsNy42MiwwLDEzLjUxLDEuODMsMTcuNyw1LjQ5LDQuMTgsMy42Niw2LjI3LDguODEsNi4yNywxNS40NnYzNy44NmgtMTIuODh2LTQuNTljLTIuNDYsMS45NC01LjEyLDMuMzYtNy45NSw0LjI2LTIuODQuOS01Ljk0LDEuMzQtOS4zLDEuMzRaTTg2OC4zNywyMjEuMTZjMCwyLjU0LDEuMDgsNC41NywzLjI1LDYuMSwyLjE2LDEuNTMsNS4wNCwyLjMsOC42MiwyLjMsMi43NiwwLDUuMzItLjM5LDcuNjctMS4xOCwyLjM1LS43OCw0LjQ2LTEuOTYsNi4zMy0zLjUzdi05LjE4Yy0yLjAyLS45Ny00LjEzLTEuNy02LjMzLTIuMTgtMi4yLS40OC00LjYxLS43My03LjIyLS43My0zLjgxLDAtNi44MS43NS05LjAyLDIuMjQtMi4yLDEuNS0zLjMsMy41NS0zLjMsNi4xNloiLz4KICAgIDxwYXRoIGNsYXNzPSJjbHMtMSIgZD0iTTkxOS41NSwyMzguMDd2LTc4LjRsMTMuMS0yLjM1djgwLjc1aC0xMy4xWiIvPgogIDwvZz4KPC9zdmc+

dynamicPlugins:
  frontend:
    default.main-menu-items:
      menuItems:
        default.mycatalog:
          title: Browse
          icon: home
          to: /wizard/catalog
          priority: 120
        default.myitem:
          title: My items
          icon: category
          to: /wizard/my-items
          priority: 110
        default.home:
          title: ''
          icon: home
          to: /
          priority: 100
        default.catalog:
          title: ''
          icon: category
          to: catalog
          priority: 80
        default.apis:
          title: ''
          icon: extension
          to: api-docs
          priority: 70
        default.learning-path:
          title: ''
          icon: school
          to: learning-paths
          priority: 60
        default.create:
          title: ''
          icon: add
          to: create
          priority: 50
    internal.plugin-dynamic-plugins-info:
      appIcons:
        - name: pluginsInfoIcon
          importName: PluginsInfoIcon
        - name: adminIcon
          importName: AdminIcon
      menuItems:
        admin:
          title: ''
          icon: adminIcon
        plugins:
          parent: admin
          title: RBAC
          to: rbac
          icon: pluginsInfoIcon
        licensing:
          parent: admin
          title: Licensing
          to: licensing
          icon: pluginsInfoIcon

ansible:
  rhaap:
    baseUrl: ${RHAAP_HOST}
    token: ${RHAAP_TOKEN}
    checkSSL: false
    showCaseLocation:
      type: file
      target: '/tmp/aap-showcases/'
    schedule:
      frequency:
        seconds: 120
      timeout:
        seconds: 5
  creatorService:
    baseUrl: '127.0.0.1'
    port: '8000'

catalog:
  stitchingStrategy:
    immediate: true
  orphanStrategy: delete
  processingInterval: { seconds: 10 }
  pollingInterval: { seconds: 1 }
  stitchTimeout: { minutes: 1 }
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        [Component, System, Group, Resource, Location, Template, API, Users]
  locations:
    - type: url
      target: https://github.com/ansible/ansible-rhdh-templates/blob/main/seed.yaml
      rules:
        - allow: [Template]
    - type: file
      target: /tmp/aap-showcases/all.yaml
      rules:
        - allow: [Template]
  providers:
    rhaap:
      development:
        schedule:
          frequency: { minutes: 5 }
          timeout: { seconds: 5 }
enableExperimentalRedirectFlow: true
