includes:
  - dynamic-plugins.default.yaml
plugins:
  - package: /opt/app-root/src/local-plugins/ansible-backstage-plugin-catalog-backend-module-rhaap-0.1.0.tgz
    disabled: false
  - package: /opt/app-root/src/local-plugins/ansible-plugin-scaffolder-backend-module-backstage-rhaap-1.1.0.tgz
    disabled: false
  - package: /opt/app-root/src/local-plugins/ansible-backstage-plugin-wizard-catalog-0.1.0.tgz
    disabled: false
    pluginConfig:
      dynamicPlugins:
        frontend:
          ansible.backstage-plugin-wizard-catalog:
            dynamicRoutes:
              - importName: WizardCatalogPage
                path: /wizard/*
